# Generated by Django 5.0.6 on 2024-07-03 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="session_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Номер сессии"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="url",
            field=models.URLField(
                blank=True, max_length=400, null=True, verbose_name="Ссылка на оплату"
            ),
        ),
    ]
